### ISSUE TITLE
[Feature request] Video time

### ISSUE THREAD

**Issue by hubertnnn** [chojnicki/video-platforms-parser#4]
Would be nice if you could add the time field to the API that will return length of video in seconds.

**Comment by chojnicki** [comment]
Added in 1.1.0.

Unfortunately, LiveLeak and Facebook (without API) doesn't provide info about duration in any way. I spend long time trying to get this info directly from small chunk of .mp4 using getID3 or own code analyzing binary data but it worked in like half of videos because in many of them required atom is placed at the end of file instead of beginning (so whole file needs to be downloaded to analyze). Because of this I decided to not publish this and for now release support for other platforms alone instead.

In case of Facebook, duration will be provided soon with official API support (but for now I do not have verified app in FB so that's why it's not ready).

In case of LiveLeak I have contacted them asking for any support in duration info on their side, like in meta tag or somewhere else in source. I'm waiting for response (but really without any real hopes).

I'm leaving this issue opened by now if You have any question or You can tell me for what platform you need this duration feature. Or maybe someone else has ideas for missing platforms ;)
