### ISSUE TITLE
[Feature request] Add video dimensions and aspect ratio

### ISSUE THREAD

**Issue by philippdaun** [chojnicki/video-platforms-parser#5]
When putting together websites, I often need to know the dimensions of a video for styling and other calculations (width, height and the resulting aspect ratio).

How do you feel about passing along that data to the parsed output, where found by the API?

I could currently use the thumbnail as proxy, but those aren't always the same format as the video (many video thumbnails unfortunately are cropped or have black bars added).

**Comment by chojnicki** [comment]
I will look into that soon

**Comment by chojnicki** [comment]
Unfortunately if I add this, in many cases it will be inaccurate exactly like You did with thumbnails.

For example YouTube in API does not provide dimensions so there is not even an options for that (except taking thumbnail sizes).
Without API (while parsing video page) there are og:tag's video:width and video:height but they are just copy of thumbnail size. 3840x2160 YT shows like 1280x720 (aspect ratio is the same so that's not bad) but non standard resolution 640x272 is 480x360 (like thumbnail with bars).

Only accurate option would be downloading video (or part of it) and analyze. But this is not good option for this package due to slower speed and high network usage.

**Comment by philippdaun** [comment]
I can see the problem. Thanks for looking into it!
